language: cpp

os:
  - linux

dist: trusty
sudo: required

compiler:
  - gcc
  - clang

notifications:
 email:
   on_success: change
   on_failure: always

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get upgrade -y
  - wget http://sourceforge.net/projects/boost/files/boost/1.68.0/boost_1_68_0.tar.bz2
  - tar jxf boost_1_68_0.tar.bz2
  - sudo cp -r boost_1_68_0/boost /usr/local/include

install:
  - g++ -v
  - clang -v
  - cmake --version

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  - cd $TRAVIS_BUILD_DIR/build
  - make
  - ./config-ctor
