language: cpp

os:
  - linux

compiler:
  - gcc

notifications:
 email:
   on_success: change
   on_failure: always

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install g++-4.8 libboost-dev cmake

install:
  - mkdir -p $TRAVIS_BUILD_DIR/build
  - cd $TRAVIS_BUILD_DIR
  - cmake ..

script:
  - "cd $TRAVIS_BUILD_DIR/build"
  - "make"
  - "./config-ctor"
